Nyholm/psr7

src/Httplug/DiscoveryStrategy.php

With this strategy it will be easy to use our factories with HTTPlug auto discovery

Added discovery strategy

---

src/Factory/ServerRequestFactory.php
src/Factory/StreamFactory.php
src/Factory/UploadedFileFactory.php

Added warning about php-interop

---

src/MessageTrait.php
src/Request.php
src/ServerRequest.php
src/Stream.php
src/UploadedFile.php
src/Uri.php

Adding more type annotations

---

.travis.yml
composer.json
tests/RequestTest.php
tests/ResponseTest.php
tests/ServerRequestTest.php
tests/StreamTest.php
tests/UploadedFileTest.php
tests/UriTest.php

Use PHPUnit 7

---

CHANGELOG.md

Added changelog for 0.3.0

---

.travis.yml
tests/RequestTest.php
tests/ResponseTest.php
tests/ServerRequestTest.php
tests/UploadedFileTest.php
tests/UriTest.php

- Unite the related ```exception``` tests.
- Some tests use the ```dataProvider``` to make tests readable.

Test enhancement

---

src/Factory/ServerRequestFactory.php

Fix a little mistake in **ServerRequestFactory** class about **createServerRequestFromGlobals()** function.

Use the local $server variable instead global $_SERVER

---

src/Factory/StreamFactory.php
src/Request.php
src/Response.php
src/ServerRequest.php
src/UploadedFile.php
src/Uri.php

Added strict comparisons and some type annotations

---

src/Factory/MessageFactory.php
src/Factory/ServerRequestFactory.php
src/Factory/StreamFactory.php
src/Factory/UriFactory.php
src/Request.php
src/RequestTrait.php
src/Response.php
src/ServerRequest.php
src/Stream.php
src/UploadedFile.php
src/Uri.php
tests/UriTest.php

This will fix #31. 
Im not sure I like the "trick" with the `RequestTrait` I had to do because the `ServerRequest` was extending `Request. `

Make all classes final

---

README.md

Document simple usage

---

composer.json
src/Factory/Psr17Factory.php
src/Factory/ServerRequestFactory.php

~~~~(it is not tagged yet)~~~~
It is tagged!

Use the PSR17 package

---

src/MessageTrait.php

Better validate headers

---

CHANGELOG.md

Release is blocked by #48 and #55.

Added changelog for 0.4.0

---

src/MessageTrait.php

Removed unneeded call to factory

---

src/Stream.php
src/UploadedFile.php

Prefix constants with backslash

---

src/MessageTrait.php

See tests here https://github.com/Nyholm/http-client-benchmark

Reduce the execution path to speed up performance

---

README.md

adds a short explanation, a link to the package, and clarifies the example a bit

Clarify what the psr7-server package is

---

README.md

@Zegnat are you fine with this?

Added a section in the readme with the goal for this library

---

src/Factory/HttplugFactory.php
src/Factory/Psr17Factory.php
src/Request.php
src/Response.php
src/Stream.php
src/UploadedFile.php
src/Uri.php

See code review for explanation.

Various code optimizations

---

README.md

Updating comparison table with new data now when Diactoros 2 is out

---

src/Request.php
src/Response.php
src/ServerRequest.php

Added comments to explain what passing body=null to ServerRequest means

---

CHANGELOG.md

Prepare for 1.1.0

---

.scrutinizer.yml

I also made this PR to see if the build is still red

Fixed a small typo

---

README.md

Change `ServerRequestCreator` to `\Nyholm\Psr7Server\ServerRequestCreator`

Fix namespace in readme

---

.github/workflows/bc.yml
.github/workflows/static.yml
.travis.yml
phpstan.neon.dist

We just got granted the Beta program

Added Github Action

---

.gitattributes

Remove . prefix from phpstan.neon.dist
Fixes https://github.com/Nyholm/psr7/issues/125

Add .github to .gitattributes

---

CHANGELOG.md

Change log for 1.3.0. After this is merged I want to tag a release. 
Diff: https://github.com/Nyholm/psr7/compare/1.2.1...master

Prepare 1.3.0

---

src/Stream.php
tests/StreamTest.php

fix https://github.com/Nyholm/psr7/issues/153

fix throw exception on read stream

---

src/Response.php

Just to make it a bit more clear what happening

Improve exception message

---

.github/workflows/static.yml
psalm.xml

I also locked/fixed the version of other checks.

Added psalm action

---

.github/workflows/branch-alias.yml

Just to make sure we never forget =)

Add Github action to automatically update branch alias

---

CHANGELOG.md

See [diff](https://github.com/Nyholm/psr7/compare/1.3.1...master). It is quite large but there are no real code changes.

Prepare release 1.3.2

---

src/Factory/Psr17Factory.php
src/Stream.php
src/UploadedFile.php
src/Uri.php
tests/RequestTest.php

@Zegnat do you have a strong opinion about this?

Make more clear exception messages with quotes

---

.gitattributes

add doc/ and psalm.xml to .gitattributes

---

CHANGELOG.md

Release 1.5.1

---

phpstan.baseline.dist
src/MessageTrait.php
src/RequestTrait.php
src/ServerRequest.php
src/Stream.php
src/UploadedFile.php
src/Uri.php
tests/RequestTest.php

And some tweaks to bring consistency regarding final dots in exception messages.

Add some missing type checks on arguments

---

.php-cs-fixer.dist.php
psalm.baseline.xml
src/Factory/Psr17Factory.php
src/MessageTrait.php
src/RequestTrait.php
src/Response.php
src/ServerRequest.php
src/Stream.php
src/UploadedFile.php
src/Uri.php
tests/StreamTest.php
tests/UploadedFileTest.php
tests/UriTest.php

[CS] native_function_invocation

---

README.md

Restore CI badges, the one from Travis was removed in #233.

README.md: add badges for GH Actions
