Nyholm/psr7

composer.json
src/Factory/ServerRequestFactory.php

This updates the ServerRequestFactoryInterface implementation to match the latest version. Claiming PSR-17 support in the README is now true, once again! 😀
[See the differences between 0.2.0 and 0.3.0 on GitHub.](https://github.com/http-interop/http-factory/compare/0.2.0...0.3.0)

Move to http-interop/http-factory version 0.3.0.

---

src/Factory/ServerRequestFactory.php
src/Factory/UriFactory.php
src/ServerRequest.php
tests/ServerRequestTest.php

**WORK IN PROGRESS, DO NOT MERGE.**
First and foremost: this changes the public API for ServerRequest, BC breaks need to be documented. (Or not, seeing how we are at a version below 1.0.0.)
This implements the changes from https://github.com/Nyholm/psr7/issues/3#issuecomment-292812159 but should be discussed further before merge.
1. `getUriFromGlobals` has been renamed `createUriFromArray` and has been moved from ServerRequest to UriFactory.
The signature has been changed to accept a single `$_SERVER`-structure as argument, instead of the method depending directly on the global `$_SERVER` variable.
2. `fromGlobals` has been renamed `createServerRequestFromGlobals` and has been moved from ServerRequest to ServerRequestFactory.
The signature has been changed to accept 5 separate array …

Move instantiation code to factories.

---

composer.json

Mostly small changes to make it easier for people to find this package.
Start providing `psr/http-factory-implementation`, which seems to be the virtual package most other implementers are using: [`psr/http-factory-implementation` on Packagist](https://packagist.org/providers/psr/http-factory-implementation).

Update composer.json with PSR-17 information

---

src/Factory/ServerRequestFactory.php

The return value for getServerParams cannot be set after a ServerRequest instance is created. Make sure we can assign it through the factory.
I think this is worth it for the current ServerRequestFactory implementation. Though this might soon change with the current discussion that is going on. Therefor I didn’t want to commit this to master just yet and have here for review first.

Assign return value for getServerParams in factory

---

src/MessageTrait.php
tests/RequestTest.php

Support using numeric header values without having type errors. An example use case would be the usage of the `Content-Length` header, which might be set with the result of a call to `strlen`.
In fact, this is the case that caught my attention, by using the latest release of the [HWIOAuthBundle](https://github.com/hwi/HWIOAuthBundle). They [use `strlen` to set the `Content-Length` header](https://github.com/hwi/HWIOAuthBundle/blob/a45c54aed8acd2da032e7e03ae53f7e44d2a384e/OAuth/ResourceOwner/AbstractResourceOwner.php#L253) when building the request headers.

Support using numeric headers

---

src/MessageTrait.php

I was using Buzz when I got an exception about empty header value.  
When I tried to use Zend Diactoros instead of this library it worked as expected.
If you'r interested I can put together a better fix that dose the validating more like it's done in [Zend Diactoros](https://github.com/zendframework/zend-diactoros/blob/master/src/HeaderSecurity.php#L96-L120)

Remove check for empty header string value

---

src/MessageTrait.php

It looks like the [RFC-7230](https://tools.ietf.org/html/rfc7230#section-3.2) require header-value to be at least 1 charecter long. But I might be wrong.
What I can find most clients/librarys allow sending of empty header values
- curl allow you to send empty headers
- Firefox allows it for xhr/fetch with the motivation `We need it to be compliant with the XHR spec: "The empty string is legal and represents the empty header value."`
- From the firefox thread it seams like Chrome also support sending and reciving empty header values
- Guzzle support sending empty header-value https://github.com/guzzle/guzzle/pull/1915

Rephrase exception messages related to non empty header values

---

src/Factory/Psr17Factory.php
src/Factory/StreamFactory.php
src/MessageTrait.php
src/Request.php
src/Response.php
src/ServerRequest.php
src/Stream.php
src/UploadedFile.php
tests/Integration/StreamTest.php
tests/StreamTest.php

Im not sure what to do here. Is this a good solution? 
The logic is copied from `StreamFactory`. 
The alternative would be to create a new public method on `Stream` and **move** the code from `StreamFactory`.

Duplicated logic to avoid creating new instance of StreamFactory

---

src/MessageTrait.php
src/RequestTrait.php
src/Response.php
src/ServerRequest.php
src/Stream.php
src/UploadedFile.php
src/Uri.php

Further change coming out of #71, this specifies certain functions as coming from the root namespace.
Only functions on [this list of optimised functions](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/b38da665fb73a25cdbc8311b439b7298fb50911c/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php#L347-L394) have been prefixed.

Pin specific functions to root namespace for optimisation

---

src/Factory/Psr17Factory.php

I noticed this because of Nyholm/psr7-server#20. It looked like we were assuming `fopen` to always succeed rather than checking, this would even leek the PHP E_WARNING to the end-user.
This PR will suppress the E_WARNING (even the PHP manual tells us we might want to do that) and explicitly check for failure. If the file couldn’t be opened, it throws a `RuntimeException` in accordance with the PSR-17 definition.

Handle fopen failing in createStreamFromFile: throw a RuntimeException.

---

tests/RequestTest.php

Resolves #82. Hopefully for good. Haha.
We do not have separate tests for the MessageTrait. I have chosen to only test this in the tests for Request objects. Should this be duplicated to Response and ServerRequest? My first thought was no.

Add tests for empty header names and values

---

src/Factory/Psr17Factory.php

Check matches PHP’s own [fopen modes parser](https://github.com/php/php-src/blob/217159d57a083908823b6d9e356ccde14abf37dc/main/streams/plain_wrapper.c#L64).

Differentiate faulty mode from other failures

---

src/Response.php

In `Response->withStatus()` $code was cast to int twice.

Remove useless cast int

---

README.md

Use the same variable names throughout the usage examples, always use absolute class paths, and use a more complete example for emitting a full HTTP response.
Closes #113.

Clean-up usage section

---

src/Uri.php
tests/UriTest.php

Listening on an unix socket reports port number 0, which is interpreted as an invalid argument.

Change minimal port number to 0 (unix socket)

---

src/Response.php
tests/ResponseTest.php

This addresses [the issue noticed in the discussion around #117](https://github.com/Nyholm/psr7/pull/117#issuecomment-487383940). This is purely to fix that one bug, I have not tested other usage of `$reasonPhrase`, not do I make any steps on resolving the core discussion of #117 and #118.
We may need to revise our thinking around `$reasonPhrase` for a 2.0 release (if we want to strictly adhere to semver).

Fix null reason phrase resulting from Response constructor

---

src/Stream.php
tests/StreamTest.php

Userland stream wrappers always return true for the "seekable" metadata, yet this can be wrong. Here is a more accurate check.

Fix checking for seekable stream resources

---

src/Factory/Psr17Factory.php
tests/Factory/Psr17FactoryTest.php
tests/ResponseTest.php

Follow up form #118 
This PR also changes the behavior if you call `$psr17Factory->createResponse(200)`. 
Before we did not give any reason phrase, now we do. Is this a BC break? It is still fine according to PSR17.

Added test to make sure we can create response with empty reason phrase

---

src/LowercaseTrait.php
src/MessageTrait.php
src/Uri.php
tests/UriTest.php

Add locale-independent lowercasing

---

composer.json
src/Stream.php
tests/StreamTest.php

Fix #142
On PHP 7.4, `__toString()` can throw.
And before PHP  7.4, `__toString()` can throw also, when the Symfony ErrorHandler is used: https://github.com/symfony/symfony/blob/e46495499841f805ab1915643f763d736d24822e/src/Symfony/Component/ErrorHandler/ErrorHandler.php#L498-L503
This fixes tests meanwhile.

Make __toString() compatible with throwing

---

src/MessageTrait.php
tests/RequestTest.php

Hello
As discussed at https://github.com/Nyholm/psr7-server/issues/35, here are some changes that seem to solve the problem.
This may be a premature PR, but it was the easiest way for me to demonstrate a cohesive solution with tests that works. @Zegnat did most of this, I just put it together.

Added support for numeric header names

---

README.md

I've forgotten that "Can be used on PHP7" was a selling point.. It is quite out dated now though.

Removed PHP7 line

---

README.md

Small PR to rename Zend to Laminas and update package & namespace references to the newer Laminas releases, after Zend became the Laminas project in January 2020.
(See https://framework.zend.com/blog/2019-04-17-announcing-laminas.html for further reference)

Rename Zend to Laminas

---

CHANGELOG.md
doc/final.md
src/Factory/HttplugFactory.php
src/Factory/Psr17Factory.php
src/Request.php
src/Response.php
src/ServerRequest.php
src/Stream.php
src/UploadedFile.php
src/Uri.php

I don't think there is any benefit to remove the `final` keyword. All the good software scientists and best practises says that you should never efter extend these value objects. 
However, some people insists on writing code that I don't approve of and from their perspective the `final` keyword is just annoying. 
This PR does not change the concept, but technically it allows some people to write the code they want to write even tough I consider it suboptimal. 
-----
Edit: When I read this description again, it looks that Im condescending. Im really not. Im trying to be pragmatic.

Remove final keyword

---

README.md

The lines of code was calculated with [cloc](https://github.com/AlDanial/cloc)

Update the readme with better benchmarks

---

CHANGELOG.md
composer.json
src/Factory/Psr17Factory.php
src/Stream.php
src/UploadedFile.php

`fopen()` has new behaviour where it will throw an error in PHP 8. Some projects have bumped into this, e.g. [Drupal](https://www.drupal.org/project/drupal/issues/3177541) and [the HTTP Factory tests](https://github.com/http-interop/http-factory-tests/pull/46).
This PR wraps our uses of `fopen()` to not leak the `ValueError` to library users.
Marking as WIP as I haven’t looked at tests yet. But have a look and see if these changes seem right!

Wrap fopen for PHP 8

---

CHANGELOG.md
src/Stream.php
tests/StreamTest.php

This will revert #177 so we don't introduce new behaviour. This will fix #180. 
FYI @Zegnat @dbu. The discussion in #180 stalled a bit. By reverting this we are predictable (but maybe wrong), we are also consistent between creating a stream from string compared to from resource.

Revert #177

---

src/Factory/Psr17Factory.php
src/Stream.php
src/UploadedFile.php

The current logic breaks when eg `stream_get_contents()` triggers a warning after a timeout.
See https://github.com/symfony/symfony/issues/42100 for background.
guzzle/psr7 has the same issue btw.

Improve error handling

---

src/ServerRequest.php
src/Stream.php

This will allow removing one deprecation notice from the Symfony codebase:
> Method "Psr\Http\Message\StreamInterface::getMetadata()" will return "mixed" as of its next major version. Doing the same in implementation "Nyholm\Psr7\Stream" will be required when upgrading.

Add explicit `@return mixed` phpdoc

---

src/Factory/HttplugFactory.php

This is needed to do now because symfony/error-handler triggers deprecation notices such these
```
1x: Method "Http\Message\RequestFactory::createRequest()" might add "RequestInterface" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\Factory\HttplugFactory" now to avoid errors or add an explicit @return annotation to suppress this message.
1x in DiscoveredClientsTest::testForcedDiscovery from Http\HttplugBundle\Tests\Functional
1x: Method "Http\Message\ResponseFactory::createResponse()" might add "ResponseInterface" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\Factory\HttplugFactory" now to avoid errors or add an explicit @return annotation to suppress this message.
1x in …
```

Add return types to HttplugFactory

---

src/ServerRequest.php
tests/Integration/RequestTest.php
tests/Integration/ResponseTest.php
tests/Integration/ServerRequestTest.php
tests/Integration/StreamTest.php
tests/Integration/UploadedFileTest.php
tests/Integration/UriTest.php

Alternative to https://github.com/Nyholm/psr7/pull/196
My suggestion about using `#[\ReturnTypeWillChange]` was wrong. This attribute is required only in the case of implementing SPL interfaces (like a `\ArrayAccess`, etc)
So these deprecations are triggered only from `symfony/error-handler` (with enabled debug).
Also applied changes to tests (applied automatically with running `patch-type-declarations` https://symfony.com/doc/5.4/setup/upgrade_major.html#upgrading-to-symfony-6-add-native-return-types)

Resolve symfony/error-handler deprecations

---

composer.json
src/Uri.php
tests/UriTest.php

Fix #206
Yes, this is unspecified by the PSR, but the current behavior produces broken URLs, and other mainstream implementations do the same: encoding characters that must be, while preventing double-encoding. I think this makes sense. It's more useful than an exception.

Encode userinfo (but don't double-encode)

---

src/ServerRequest.php
tests/ServerRequestTest.php

Populate ServerRequest::getQueryParams() with query string passed to constructor

---

.github/workflows/bc.yml

This reverts commit e1f7ae67056c2e932a0b77bf3be8dc05863fd3ec.
#215 didn't fix anything.

Revert "Fix permissions on BC check job"

---

.gitignore
src/Stream.php
tests/ResponseTest.php
tests/StreamTest.php

This is useful in test env where we usually 'mock' the response
This is resurrecting #98 by @lyrixx
After years of practice, this is still one of the major pain points when using PSR-7.
Let's make the life or users less surprising.
Fix #99

Stream: seek to the begining of the string on initialization

---

src/Uri.php
tests/UriTest.php

Fix #219
This is enough to produce non-broken URLs.

Encode only reserved characters in user-info

---

doc/final.md
src/Factory/HttplugFactory.php
src/Factory/Psr17Factory.php
src/Request.php
src/Response.php
src/ServerRequest.php
src/Stream.php
src/UploadedFile.php
src/Uri.php

By keeping `@final`, we'll be able to add types to arguments without issuing a new major version. This is especially important since PSR-7 v1.1 and v2.0 have been released and we're likely going to have to adopt them soon.

Revert removals of `@final` annotations

---

.github/workflows/static.yml
composer.json
phpstan-baseline.neon
src/MessageTrait.php
src/RequestTrait.php
src/Response.php
src/ServerRequest.php
src/Stream.php
src/StreamTrait.php
src/Uri.php
tests/StreamTest.php

Instead of #223 to not bump to PHP 7.2 when not needed.
Requires https://github.com/php-http/psr7-integration-tests/pull/68

Allow psr/http-message v2

---

composer.json
src/Stream.php
tests/StreamTest.php

Alternative to #227 so that we can compare both approaches.

Use zval storage for Stream instances created from strings

---

src/Stream.php
tests/StreamTest.php

Using https://github.com/devanych/psr-http-benchmark, I figured out that for strings smaller than ~200k, `php://memory` is faster than the custom zval stream. Past this threshold, zval stream is way faster thanks to copy-on-write.

Improve performance of creating streams from strings

---

CHANGELOG.md
composer.json
src/Factory/HttplugFactory.php

Follows https://github.com/php-http/message-factory/pull/42

Deprecate HttplugFactory and make dependency on php-http/message-factory optional

---

src/Factory/Psr17Factory.php
src/Response.php

Fixes all issues that emits a deprecation notice on PHP 8.4.
See:
- [RFC](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types)
- [PHP 8.4: Implicitly nullable parameter declarations deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)

[PHP 8.4] Fixes for implicit nullability deprecation
